# Generated by Django 2.0.3 on 2018-12-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shopping_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placed_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_orders', to='orders.Shopping_Cart')),
            ],
        ),
    ]
