# Generated by Django 2.0.3 on 2018-12-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_placed_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='confirmed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placed_orders',
            name='placed_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='placed_orders', to='orders.Shopping_Cart'),
        ),
    ]
