# Generated by Django 2.0.3 on 2018-12-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shopping_cart_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed_orders',
            name='placed_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_orders', to='orders.Shopping_Cart'),
        ),
    ]
