# Generated by Django 2.0.3 on 2018-12-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shopping_cart_order_pasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='order',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='order_dinner',
            field=models.ManyToManyField(blank=True, related_name='orders_dinner', to='orders.Dinner'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='order_pizza',
            field=models.ManyToManyField(blank=True, related_name='orders_pizza', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='order_salads',
            field=models.ManyToManyField(blank=True, related_name='orders_salads', to='orders.Salads'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='type',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
    ]
