# Generated by Django 2.0.3 on 2018-12-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_addon_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='addons', to='orders.AddOn'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='order_subs',
            field=models.ManyToManyField(blank=True, related_name='orders_subs', to='orders.Subs'),
        ),
    ]
